### ISSUE TITLE
Detects spurious "phantom" tags

### ISSUE THREAD

**Issue by DavidB-CMU** [personalrobotics/apriltags#18]
I was testing this node with tag No. 1 from the default 36h11 family.

Often it will detect phantom tags that are not in the scene.
e.g. I was moving around "tag1" 
but it made spurious detections of "tag348" and "tag140"

I leave the node running and it detects more phantom tags 
e.g. 371, 460, 379, 572, 296, 223

see the following screenshot: 
![apriltag_swatbotics_spurious_detections](https://cloud.githubusercontent.com/assets/14189705/14221135/aa8781da-f832-11e5-84f9-3b7629833d6b.png)

This bug is now hidden by a change I made (PR https://github.com/personalrobotics/apriltags/pull/17) to make published markers disappear after 0.5 seconds.

**Comment by psigen** [comment]
@DavidB-CMU: I think these are legitimate false positives generated by the underlying AprilTags library.  Missed detections can occur from areas of high-frequency texture, where the checks for a rectilinear region with a particular checksum might pass by pure chance.

The 36h11 tags should be using 15-bits (`36 - 11 = 15`) of redundancy, so these detections would normally be quite rare.  Given the  guessing that there is some sort of extremely high-frequency texture right in the 2D image region where the false detections are generated.  This could be some sort of high-contrast pattern, or a partially obscured AprilTag.

In any case, the recourses are probably:
1. Switch to a tag family with even more bits of redundancy (e.g. 36h10 or something like that).
2. Switch the underlying AprilTags library to a different implementation that might have more rigorous checks for false positives.
3. Implement spatiotemporal filtering/tracking.  I think this makes sense to do on a higher level, like in `prpy.perception`, but is probably outside the scope of the AprilTags ROS node functionality.

I'm going to close this for now, since I'm not sure there's anything to change on the ROS node to fix this.  We can open a new issue for (2), as there was interest in trying out e.g. Michael Kaess's library, and we can also open an issue on https://github.com/swatbotics/apriltags-cpp if we want to try to improve the Swatbotics library false positive rate.
